name: SonarQube Analysis (CLI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:x
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SonarQube Scanner
        run: |
          npm install -g sonarqube-scanner

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=meu-projeto \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN